config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'about', to: 'home#about'

  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  root to: redirect('users/sign_in')

  resources :questions

  resources :questions do
    resources :answers  do
      member do
        put 'like', to: "answers#upvote"
        put 'dislike', to: "answers#downvote"
      end
    end
  end
end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.role == 'admin'
        can :manage, :all
    else
        can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question, :counter_cache => true
  acts_as_votable
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :questions, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])

    if params[:sort_time]
      @answers = Answer.where(:question_id => params[:question_id]).sort_by{ |a| a.created_at}.reverse!
    elsif params[:sort_votes]
      @answers = Answer.where(:question_id => params[:question_id]).sort_by{|a| a.cached_weighted_score}.reverse!
    else
      @answers = Answer.where(:question_id => params[:question_id])
    end
  end

  def upvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.upvote_by current_user
    redirect_to question_answers_path
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.downvote_by current_user
    redirect_to question_answers_path
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to question_answers_path
    else
      render 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
      redirect_to question_answers_path
    else
      render 'edit'
    end
  end

  def destroy
    Answer.find(params[:id]).destroy
    redirect_to question_answers_path
  end

  private

  def answer_params
    params.require(:answer).permit(:description, :upvote, :downvote).merge(:question_id => params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @answers = Answer.all

    if params[:mine]
      @questions = current_user.questions

    elsif params[:sort_time]
      @questions = Question.all.sort_by{ |q| q.created_at}.reverse!

    elsif params[:sort_answers]
      @questions = Question.all.sort_by{ |q| q.answers_count}.reverse!

    else
      @questions = Question.all
    end
  end

  def about
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to authenticated_root_path
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to question_answers_path
    else
      render 'edit'
    end
  end

  def destroy
    Question.find(params[:id]).delete
    redirect_to authenticated_root_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :upvote, :downvote, :user_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answers_form.html.erb
<div class='feed'>

<div class='well'>
  <span style="font-weight:bold; font-size: 16px"><%= @question.title %></span>
</div>
<div class='well'>
  <%= @question.description %>
</div>

<%= form_for( @answer, url: question_answers_path(params[:question_id]), html: {class: 'form-signin', style: 'padding-bottom: 5px'}) do |f| %>
  <%= f.label :description, class: 'sr-only' %>
  <%= f.text_area :description, class: 'form-control', size: '40x10', placeholder: 'Well actually...' %>
  <%= f.submit 'Submit', class: 'btn btn-lg btn-primary btn-block', style: 'margin-top: 5px' %>
<% end %>

<%= link_to 'Cancel', authenticated_root_path %>

app/views/answers/edit.html.erb
<%= render 'answers_form' %>

app/views/answers/index.html.erb
<div class="button-column">
  <div class="well sort-button">
  <%= link_to 'Sort by Most Recent', question_answers_path(params.merge(:sort_time => true, :sort_votes => nil)) %>
  </div>
  <div class="well sort-button">
  <%= link_to 'Sort by Most Popular', question_answers_path(params.merge(:sort_votes => true, :sort_time => nil)) %>
  </div>
  <div class="well sort-button">
  <%= link_to 'Return to Questions', authenticated_root_path %>
  </div>
</div>


<div class='feed'>

<div class='well'>
  <span style="font-weight:bold; font-size: 16px"><%= @question.title %></span>
</div>
<div class='well'>
  <%= @question.description %>
</div>

<% if @answers.count == 0 %>
  <div class='well well-sm'>This question hasn't been answered <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>

  <%= link_to('Answer', new_question_answer_path(@question[:id])) %>

  <% if can? :destroy, a %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold"> //</span>

    <%= link_to "Delete", {:controller => :answers, :action => 'destroy', :id => a.id}, :method => :delete %>
    <% end %>
  </div>

<% else %>
  <% @answers.each do |a| %>
    <div class='well'><%= a.description%></div>
    <div class='well well-sm'>

    <%= link_to '+ ', like_question_answer_path(@question, a), method: :put %><%=a.get_upvotes.size %> upvotes<span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold"> //</span>

    <%= link_to '- ', dislike_question_answer_path(@question, a), method: :put %><%=a.get_downvotes.size%> downvotes<span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold"> //</span>

    <%= link_to('Answer', new_question_answer_path(@question[:id])) %>

    <% if can? :destroy, a %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold"> //</span>

    <%= link_to "Delete", {:controller => :answers, :action => 'destroy', :id => a.id}, :method => :delete %>
    <% end %>
    </div>

  <% end %>
<% end %>

</div>

app/views/answers/new.html.erb
<%= render 'answers_form' %>

app/views/home/about.html.erb
<div class="well">
  Polity is a basic question-and-answer forum. Users can ask and answer questions, as well as vote on answers. Questions can be sorted by time created or number of answers, while answers can be sorted by time created and popularity. Users can also choose to view only questions they themselves asked.
</div>

app/views/home/index.html.erb
<div class="button-column">
  <div class="well sort-button">
  <%= link_to 'Sort by Most Recent', authenticated_root_path(:sort_time => true) %>
  </div>
  <div class="well sort-button">
  <%= link_to 'Sort by Most Popular', authenticated_root_path(:sort_answers => true) %>
  </div>
  <div class="well sort-button">
  <%= link_to 'My Questions', authenticated_root_path(:mine => true) %>
  </div>
</div>

<div class='feed'>

<% @questions.each do |q| %>

<% if can? :destroy, q %>

  <div class='well'><%= q.title %></div>

  <% if q.answers_count == 1 %>

    <div class='well'>
    This question has 1 response so far
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('View Answers', question_answers_path(q[:id])) %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('Answer', new_question_answer_path(q[:id])) %>
    </div>

    <div class='well well-sm'>
    <%= link_to "Delete", {:controller => :questions, :action => 'destroy', :id => q.id}, :method => :delete %>
    </div>

  <% else %>

    <div class='well'>
    This question has <%= q.answers_count %> responses so far
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('View Answers', question_answers_path(q[:id])) %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('Answer', new_question_answer_path(q[:id])) %>
    </div>

    <div class='well well-sm'>
    <%= link_to "Delete", {:controller => :questions, :action => 'destroy', :id => q.id}, :method => :delete %>
    </div>

  <% end %>

<% else %>

  <% if q.answers_count == 1 %>

    <div class='well well-sm'>
    This question has 1 response so far
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('View Answers', question_answers_path(q[:id])) %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('Answer', new_question_answer_path(q[:id])) %>
    </div>

  <% else %>

    <div class='well well-sm'>
    This question has <%= q.answers_count %> responses so far
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('View Answers', question_answers_path(q[:id])) %>
    <span style="color: rgb(51, 122, 183); padding-left: 2px; padding-right: 2px; font-weight: bold">//</span>
    <%= link_to('Answer', new_question_answer_path(q[:id])) %>
    </div>

  <% end %>

<% end %>

<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polity</title>
  <%= stylesheet_link_tag 'application', '//fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<% if user_signed_in? %>
<div class="container"</div>
  <nav>
  <div class="nav masthead-brand"><%=link_to 'POLITY', authenticated_root_path%> <span style="font-size: 12px">//a Wilson Center project</div>
  <ul class="nav masthead-nav">
     <li>
       <%= link_to('About', about_path) %>
     <li>
       <%= link_to('Ask a Question', new_question_path)%>
     </li>
     <li>
       <%= link_to('My Account', edit_user_registration_path) %>
     </li>
     <li>
       <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
     </li>
  </ul>
  </nav>
</div>
<% else %>
<div class="banner"> POLITY </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/_questions_form.html.erb
<%= form_for(@question, html: {class: 'form-signin', style: 'padding-bottom: 5px'}) do |f| %>
  <%= f.label :title, class: 'sr-only' %>
  <%= f.text_field :title, class: 'form-control', placeholder: "My question, in brief:" %>
  <br>
  <br>
  <%= f.label :description, class: 'sr-only' %>
  <%= f.text_area :description, class: 'form-control', size: '40x10', placeholder: 'You can elaborate here.' %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit 'Submit', class: 'btn btn-lg btn-primary btn-block', style: 'margin-top: 5px' %>
<% end %>

<%= link_to 'Cancel', authenticated_root_path %>

app/views/questions/new.html.erb
<%= render 'questions_form' %>